# Generated by Django 3.1.4 on 2020-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitaingrediente',
            name='quantidade_ingrediente',
        ),
        migrations.AlterField(
            model_name='receitaingrediente',
            name='ingrediente',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
