# Generated by Django 3.1.4 on 2020-12-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201210_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacoesReceita',
            new_name='InformacaoReceita',
        ),
    ]
