# Generated by Django 3.1.4 on 2020-12-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201210_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceitaIngrediente',
            new_name='IngredienteReceita',
        ),
    ]
