# Generated by Django 3.1.4 on 2020-12-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201210_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preparo',
            new_name='ModoPreparo',
        ),
    ]
